export const countryCodeToName: Record<string, string> = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AD: "Andorra",
  AO: "Angola",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo (DRC)",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GR: "Greece",
  GD: "Grenada",
  GT: "Guatemala",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  CI: "Ivory Coast",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MK: "North Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MR: "Mauritania",
  MU: "Mauritius",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SZ: "Eswatini",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const countryCodeToCurrency: Record<string, string> = {
  AF: "Af",
  AL: "L",
  DZ: "DA",
  AD: "€",
  AO: "Kz",
  AG: "$",
  AR: "$",
  AM: "֏",
  AU: "A$",
  AT: "€",
  AZ: "₼",
  BS: "$",
  BH: "BD",
  BD: "৳",
  BB: "$",
  BY: "Br",
  BE: "€",
  BZ: "$",
  BJ: "Fr",
  BT: "Nu",
  BO: "Bs.",
  BA: "KM",
  BW: "P",
  BR: "R$",
  BN: "$",
  BG: "лв",
  BF: "Fr",
  BI: "Fr",
  KH: "៛",
  CM: "Fr",
  CA: "C$",
  CV: "$",
  CF: "Fr",
  TD: "Fr",
  CL: "$",
  CN: "¥",
  CO: "$",
  KM: "Fr",
  CG: "Fr",
  CD: "Fr",
  CR: "₡",
  HR: "€",
  CU: "$",
  CY: "€",
  CZ: "Kč",
  DK: "kr",
  DJ: "Fr",
  DM: "$",
  DO: "$",
  EC: "$",
  EG: "£",
  SV: "$",
  GQ: "Fr",
  ER: "Nfk",
  EE: "€",
  ET: "Br",
  FJ: "$",
  FI: "€",
  FR: "€",
  GA: "Fr",
  GM: "D",
  GE: "₾",
  DE: "€",
  GH: "₵",
  GR: "€",
  GD: "$",
  GT: "Q",
  GN: "Fr",
  GW: "Fr",
  GY: "$",
  HT: "G",
  HN: "L",
  HU: "Ft",
  IS: "kr",
  IN: "₹",
  ID: "Rp",
  IR: "﷼",
  IQ: "ع.د",
  IE: "€",
  IL: "₪",
  IT: "€",
  CI: "Fr",
  JM: "$",
  JP: "¥",
  JO: "JD",
  KZ: "₸",
  KE: "KSh",
  KI: "$",
  KP: "₩",
  KR: "₩",
  KW: "KD",
  KG: "с",
  LA: "₭",
  LV: "€",
  LB: "£",
  LS: "L",
  LR: "$",
  LY: "LD",
  LI: "Fr",
  LT: "€",
  LU: "€",
  MK: "ден",
  MG: "Ar",
  MW: "MK",
  MY: "RM",
  MV: "Rf",
  ML: "Fr",
  MT: "€",
  MH: "$",
  MR: "UM",
  MU: "Rs",
  MX: "$",
  FM: "$",
  MD: "L",
  MC: "€",
  MN: "₮",
  ME: "€",
  MA: "MAD",
  MZ: "MT",
  MM: "K",
  NA: "$",
  NR: "$",
  NP: "Rs",
  NL: "€",
  NZ: "NZ$",
  NI: "C$",
  NE: "Fr",
  NG: "₦",
  NO: "kr",
  OM: "RO",
  PK: "₨",
  PW: "$",
  PS: "₪",
  PA: "B/.",
  PG: "K",
  PY: "₲",
  PE: "S/",
  PH: "₱",
  PL: "zł",
  PT: "€",
  QA: "QR",
  RO: "lei",
  RU: "₽",
  RW: "Fr",
  KN: "$",
  LC: "$",
  VC: "$",
  WS: "T",
  SM: "€",
  ST: "Db",
  SA: "SR",
  SN: "Fr",
  RS: "din",
  SC: "Rs",
  SL: "Le",
  SG: "S$",
  SK: "€",
  SI: "€",
  SB: "$",
  SO: "Sh",
  ZA: "R",
  SS: "£",
  ES: "€",
  LK: "Rs",
  SD: "£",
  SR: "$",
  SZ: "L",
  SE: "kr",
  CH: "Fr",
  SY: "£",
  TW: "NT$",
  TJ: "SM",
  TZ: "TSh",
  TH: "฿",
  TL: "$",
  TG: "Fr",
  TO: "T$",
  TT: "$",
  TN: "DT",
  TR: "₺",
  TM: "T",
  TV: "$",
  UG: "USh",
  UA: "₴",
  AE: "AED",
  GB: "£",
  US: "$",
  UY: "$U",
  UZ: "so'm",
  VU: "Vt",
  VA: "€",
  VE: "Bs.",
  VN: "₫",
  YE: "﷼",
  ZM: "ZK",
  ZW: "$",
};